services:
  postgres:
    image: postgres:16
    container_name: crud-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  crud-api:
    build: .
    container_name: crud-api
    restart: unless-stopped

    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres:5432/crud_db
      PORT: 3000
      NODE_ENV: production
  
volumes:
  postgres_data:

