---
- name: Install Docker
  shell: curl -fsSL https://get.docker.com | sh

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Enable Docker
  service:
    name: docker
    enabled: yes
    state: started
